// swift-tools-version: 5.8

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "CreativePad",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "CreativePad",
            targets: ["AppModule"],
            bundleIdentifier: "wwdc2024.CreativePad",
            teamIdentifier: "UBAV753C5G",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.mint),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .fileAccess(.musicFolder, mode: .readWrite),
                .fileAccess(.downloadsFolder, mode: .readWrite),
                .fileAccess(.userSelectedFiles, mode: .readWrite),
                .microphone(purposeString: "Your recordings are not shared and are only used within the app")
            ],
            appCategory: .music
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "."
        )
    ]
)